services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=menhir'
      - 'POSTGRES_PASSWORD=alskdjfioeasoefmca'
      - 'POSTGRES_USER=menhir'
    ports:
      - '5432:5432'
